// Generated by https://quicktype.io
import 'dart:convert';

ImageApiModel welcomeFromJson(String str) =>
    ImageApiModel.fromJson(json.decode(str));

class ImageApiModel {
  String? href;
  List<Datum>? data;
  List<Link>? links;

  ImageApiModel({
    this.href,
    this.data,
    this.links,
  });

  factory ImageApiModel.fromJson(Map<String, dynamic> json) => ImageApiModel(
        href: json["href"],
        data: List<Datum>.from(json["data"].map((x) => Datum.fromJson(x))),
        links: List<Link>.from(json["links"].map((x) => Link.fromJson(x))),
      );
}

class Datum {
  String? center;
  String? title;
  String? photographer;
  List<String>? keywords;
  String? location;
  String? nasaId;
  String? mediaType;
  String? dateCreated;
  String? description;
  String? secondarycreator;

  Datum({
    this.center,
    this.title,
    this.photographer,
    this.keywords,
    this.location,
    this.nasaId,
    this.mediaType,
    this.dateCreated,
    this.description,
    this.secondarycreator,
  });

  factory Datum.fromJson(Map<String, dynamic> json) => Datum(
        center: json["center"],
        title: json["title"],
        photographer: json["photographer"] ?? '',
        keywords: json["keywords"] == null
            ? []
            : List<String>.from(json["keywords"].map((x) => x)),
        location: json["location"],
        nasaId: json["nasa_id"],
        mediaType: json["media_type"],
        dateCreated: json["date_created"],
        description: json["description"],
        secondarycreator: json["secondary_creator"] ?? '',
      );
}

class Link {
  String? href;
  String? rel;
  String? render;

  Link({
    this.href,
    this.rel,
    this.render,
  });

  factory Link.fromJson(Map<String, dynamic> json) => Link(
        href: json["href"],
        rel: json["rel"],
        render: json["render"],
      );
}
