// Generated by https://quicktype.io

class TodayNasaModel {
  String? copyright;
  String? date;
  String? explanation;
  String? hdurl;
  String? mediaType;
  String? serviceVersion;
  String? title;
  String? url;

  TodayNasaModel({
    this.copyright,
    this.date,
    this.explanation,
    this.hdurl,
    this.mediaType,
    this.serviceVersion,
    this.title,
    this.url,
  });

  factory TodayNasaModel.fromMap(Map<String, dynamic> map) {
    return TodayNasaModel(
      copyright: map['copyright'],
      date: map['date'],
      explanation: map['explanation'],
      hdurl: map['hdurl'],
      mediaType: map['mediaType'],
      serviceVersion: map['serviceVersion'],
      title: map['title'],
      url: map['url'],
    );
  }
}
